### ISSUE TITLE
Crash when opening Dialog

### ISSUE THREAD

**Issue by DenisMondon** [openkwaky/ratingreminder#3]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.radiofrance.rfpodcasts/fr.radiofrance.rfpodcasts.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int net.equasoft.ratingreminder.type.RatingDialogType.ordinal()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int net.equasoft.ratingreminder.type.RatingDialogType.ordinal()' on a null object reference
       at net.equasoft.ratingreminder.fragment.AskingDialogFragment.onCreateDialog(AskingDialogFragment.java:40)
       at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:598)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by openkwaky** [comment]
Hello,

Try last version v1.7, it should fix that

**Comment by DenisMondon** [comment]
Wow, you're too fast!! Awesome! I will try it soon ;) Thx
